GET http://localhost:3000/login

###

GET http://localhost:3000/users/65655776698c2647964b9f60

###

POST http://localhost:3000/login
Content-Type: application/json

{
  
    "email": "jawo@gmail.com",
    "password":"1234"
}
