GET http://localhost:3000/facilatators
Content-Type: application/json
# Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY1NWU5YmFjMzViZGM2N2NlOGQ0YzUiLCJmaXJzdE5hbWUiOiJKYXdvIiwibGFzdE5hbWUiOiJEaWF6IiwidXNlclJvbGUiOiJDaGVzcyIsImlhdCI6MTcwMTI1MTAyOSwiZXhwIjoxNzAxMjUxNjI5fQ.jsHbyHlDnjmNAF8KRyZE013kZ1XmhcU9dzZaS2jTAx8"

###

GET http://localhost:3000/facilatators/6539b96749e971c8453c218f

###

POST http://localhost:3000/facilatators
Content-Type: application/json
Authorization: : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY1NWU5YmFjMzViZGM2N2NlOGQ0YzUiLCJmaXJzdE5hbWUiOiJKYXdvIiwibGFzdE5hbWUiOiJEaWF6IiwidXNlclJvbGUiOiJDaGVzcyIsImlhdCI6MTcwMTI1MDY4MiwiZXhwIjoxNzAxMjUwNjkyfQ.OvomT-TjVMCwxLUB68mpt-g9zVtMwygp4WdOTi3_wi4"
{
    "firstName": "Jawo",
    "lastName": "Diaz",
    "facilitatorRole": "Coach",
    "sportsEvent":"Chess"
}

###

DELETE http://localhost:3000/facilatators/6539b7a264783bf342df4f16

###

PATCH http://localhost:3000/facilatators/6539b96249e971c8453c2183
Content-Type: application/json

{
    "firstName": "YYYYY",
    "lastName": "1111",
    "role": "3333"
}