GET http://localhost:3000/users


###

GET http://localhost:3000/users/656f4cdbdcba0ba7942660c0

###

POST http://localhost:3000/users
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTY1NWU5YmFjMzViZGM2N2NlOGQ0YzUiLCJmaXJzdE5hbWUiOiJKYXdvIiwibGFzdE5hbWUiOiJEaWF6IiwidXNlclJvbGUiOiJDaGVzcyIsImlhdCI6MTcwMTE2MTk3NiwiZXhwIjoxNzAxMTY1NTc2fQ.CRUyUIJXzB8dea7d8l-klZVTmZY4F6mheE4_o-vU0gE

{
    "firstName": "Jawo",
    "lastName": "Diaz",
    "email": "admin@gmail.com",
    "password":"1234",
    "userRole":"Admin",
    "isActive":true
}


###

DELETE http://localhost:3000/users/656f5778c0541334ff22cdb2

###

PUT http://localhost:3000/users/65655e9bac35bdc67ce8d4c5
Content-Type: application/json

{
     "firstName": "admin",
    "lastName": "admin",
    "email": "admin@gmail.com",
    "password":"jawo4321",
    "userRole":"Admin",
    "isActive":true
}